/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pvoovtkjyvhhxchmhijk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2b292dGtqeXZoaHhjaG1oaWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTcxNTIsImV4cCI6MjA3MjM5MzE1Mn0.zlOf8NDwXLy-1KLl50xqVXNPOaPBqr7QuI-LdNH7dU0"